blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/bh9g8MebJn
    about: For general help.
  - name: AlliedModder's Discord
    url: https://discord.gg/HUc67zN
    about: For general help with Sourcemod.
