name: Compile Plugins

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Compile plugin for ${{ matrix.identifier }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildjobs:
          - sourcemod-1.12
          - sourcemod-1.13

        include:

          - buildjobs: sourcemod-1.12
            os_version: ubuntu-latest
            identifier: 'Sourcemod Stable'
            sm-version: '1.12.x'
            package-name: 'sm-stable'

          - buildjobs: sourcemod-1.13
            os_version: ubuntu-latest
            identifier: 'Sourcemod Dev'
            sm-version: '1.13.x'
            package-name: 'sm-dev'
    env:
      SOURCEFILES_PATH: ${{ github.workspace }}/sourcefiles
      TPINCLUDES_PATH: ${{ github.workspace }}/thirdparty/includes
      BUILD_PATH: ${{ github.workspace }}/build/source
      PACKAGE_PATH: ${{ github.workspace }}/build/package
      CONFIGS_PATH: ${{ github.workspace }}/build/package/addons/sourcemod/configs
      SMDATA_PATH: ${{ github.workspace }}/build/package/addons/sourcemod/data
      GAMEDATA_PATH: ${{ github.workspace }}/build/package/addons/sourcemod/gamedata
      BINARY_PATH: ${{ github.workspace }}/build/package/addons/sourcemod/plugins
      LOC_PATH: ${{ github.workspace }}/build/package/addons/sourcemod/translations

    steps:
      - name: Create Folders
        run: |
          echo "Creating folders..."
          mkdir -p ${{ env.TPINCLUDES_PATH }}
          mkdir -p ${{ env.BUILD_PATH }}
          mkdir -p ${{ env.CONFIGS_PATH }}
          mkdir -p ${{ env.SMDATA_PATH }}
          mkdir -p ${{ env.GAMEDATA_PATH }}
          mkdir -p ${{ env.BINARY_PATH }}
          mkdir -p ${{ env.LOC_PATH }}

      - name: Fetch Plugins Sources
        uses: actions/checkout@v5.0.0
        with:
          path: sourcefiles

      - name: Setup SourcePawn Compiler for ${{ matrix.identifier }} ( ${{ matrix.sm-version }} )
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Fetch Third-Party Includes (WGET)
        working-directory: ${{ env.TPINCLUDES_PATH }}
        run: |
          wget https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc -O steamworks.inc
          wget https://raw.githubusercontent.com/Sarrus1/DiscordWebhookAPI/master/include/discordWebhookAPI.inc -O discordWebhookAPI.inc
          wget https://raw.githubusercontent.com/Impact123/AutoExecConfig/development/autoexecconfig.inc -O autoexecconfig.inc
          wget https://raw.githubusercontent.com/peace-maker/sourcetvmanager/master/sourcetvmanager.inc -O sourcetvmanager.inc
          wget https://raw.githubusercontent.com/nosoop/SM-SteamPawn/main/scripting/include/steampawn.inc -O steampawn.inc
          wget https://raw.githubusercontent.com/Impact123/CallAdmin/development/gameserver/scripting/include/calladmin.inc -O calladmin.inc
          wget https://raw.githubusercontent.com/FlaminSarge/tf2attributes/refs/heads/master/scripting/include/tf2attributes.inc -O tf2attributes.inc
          wget https://raw.githubusercontent.com/nosoop/SM-TFUtils/refs/heads/master/scripting/include/tf2utils.inc -O tf2utils.inc
          ls -lah

      - name: Fetch REST in SourcePawn
        uses: actions/checkout@v5.0.0
        with:
          repository: ErikMinekus/sm-ripext
          path: ripext

      - name: Fetch Left 4 DHooks Direct
        uses: actions/checkout@v5.0.0
        with:
          repository: SilvDev/Left4DHooks
          path: left4dhooks
  
      - name: Fetch SMLIB
        uses: actions/checkout@v5.0.0
        with:
          repository: bcserv/smlib
          path: smlib
          ref: transitional_syntax

      - name: Fetch MultiColors
        uses: actions/checkout@v5.0.0
        with:
          repository: Bara/Multi-Colors
          path: multicolors

      - name: Fetch shqke
        uses: actions/checkout@v5.0.0
        with:
          repository: shqke/sp_public
          path: shqkeplugins

      - name: Fetch SourceBans++
        uses: actions/checkout@v5.0.0
        with:
          repository: sbpp/sourcebans-pp
          path: sbpp

      - name: Fetch Stocksoup
        uses: actions/checkout@v5.0.0
        with:
          repository: nosoop/stocksoup
          path: stocksoup

      - name: Move Fetched Includes to Shared Includes Path
        run: |
          rsync -rv ${{ github.workspace }}/ripext/pawn/scripting/include/* ${{ env.TPINCLUDES_PATH }}/
          rsync -rv ${{ github.workspace }}/left4dhooks/sourcemod/scripting/include/* ${{ env.TPINCLUDES_PATH }}/
          rsync -rv ${{ github.workspace }}/smlib/scripting/include/* ${{ env.TPINCLUDES_PATH }}/
          rsync -rv ${{ github.workspace }}/multicolors/addons/sourcemod/scripting/include/* ${{ env.TPINCLUDES_PATH }}/
          rsync -rv ${{ github.workspace }}/shqkeplugins/.deps/include/* ${{ env.TPINCLUDES_PATH }}/
          rsync -rv ${{ github.workspace }}/sbpp/game/addons/sourcemod/scripting/include/* ${{ env.TPINCLUDES_PATH }}/
          mkdir -p ${{ env.TPINCLUDES_PATH }}/stocksoup/
          rsync -rv ${{ github.workspace }}/stocksoup/* ${{ env.TPINCLUDES_PATH }}/stocksoup/
          ls -lah ${{ env.TPINCLUDES_PATH }}/

      - name: Move Plugin Source Files to Build Directory
        run: |
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/discordstatus_v2/scripting/* ${{ env.BUILD_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/tf_mvm_credits/scripting/* ${{ env.BUILD_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/autorecorder/scripting/* ${{ env.BUILD_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/l4d_automod/scripting/* ${{ env.BUILD_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/geolanguage/scripting/* ${{ env.BUILD_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/rcbot2_randomseedfix/scripting/* ${{ env.BUILD_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/tf_bots_mvm_fixes/scripting/* ${{ env.BUILD_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/cannounce/scripting/* ${{ env.BUILD_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/gpluck/scripting/* ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/connectlog.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/l4d_antiearlyvote.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/sessionbans.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/l4d2_admin_stealth.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/sm_gamedata_tester.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/ainavfile-blocker.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/cl_cmds_logger.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/player_spawn_logger.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/autobalance_bots.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/player_movement_bug_test.sp ${{ env.BUILD_PATH }}/
          cp ${{ github.workspace }}/sourcefiles/source/simple_stopwatch.sp ${{ env.BUILD_PATH }}/

      - name: Compile Plugins
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          for file in *.sp; do
            echo -e "\nCompiling $file..."
            spcomp -v2 -i ${{ env.TPINCLUDES_PATH }}/ $file
          done
          echo "===OUT FILES==="
          ls -lah *.smx
          
      - name: Move Compiled Plugins to Package Directory
        run: |
          rsync -rv ${{ env.BUILD_PATH }}/*.smx ${{ env.BINARY_PATH }}/

      - name: Move Additional Files to Package Directory
        run: |
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/discordstatus_v2/configs/* ${{ env.CONFIGS_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/l4d_automod/configs/* ${{ env.CONFIGS_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/l4d_automod/translations/* ${{ env.LOC_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/geolanguage/configs/* ${{ env.CONFIGS_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/rcbot2_randomseedfix/gamedata/* ${{ env.GAMEDATA_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/tf_bots_mvm_fixes/gamedata/* ${{ env.GAMEDATA_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/cannounce/translations/* ${{ env.LOC_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/gamedata/* ${{ env.GAMEDATA_PATH }}/
          rsync -rv ${{ github.workspace }}/sourcefiles/plugins/gpluck/configs/* ${{ env.CONFIGS_PATH }}/

      - name: Fetch Short SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Upload Compiled Plugins Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: plugins-${{ matrix.package-name }}-${{ steps.short-sha.outputs.sha }}
          path: |
            build/package/*
      

    